// products.js — catalogue cosmétiques (placeholders SVG)
window.PRODUCTS = [
  {
    id: 'c1',
    title: 'Crème hydratante 50ml',
    price: 18.90,
    desc: 'Crème légère et non grasse formulée pour hydrater en profondeur et renforcer la barrière cutanée. Absorption rapide, idéale sous le maquillage.',
    tagline: 'Hydratation longue durée, fini naturel',
    benefits: ['Hydrate 24h', 'Renforce la barrière cutanée', 'Texture non grasse, convient au maquillage'],
    category: 'Soins',
    tags: ['nouveau'],
    img: 'images/c1.jpg',
    images: ['images/c1.jpg','images/c1.jpg','images/c1.jpg'],
    rating: 4.8,
    reviews: 142,
    testimonial: "Texture légère, hydrate toute la journée — Lina"
  },
  {
    id: 'c2',
    title: 'Sérum vitaminé 30ml',
    price: 24.50,
    desc: 'Sérum concentré en vitamines C et E pour illuminer le teint et protéger la peau des agressions environnementales. Améliore la luminosité et réduit les signes de fatigue.',
    tagline: 'Éclat instantané, peau réveillée',
    benefits: ['Illumine le teint', 'Antioxydant (protège contre les agressions)', 'Texture légère, pénétration rapide'],
    category: 'Soins',
    tags: ['bestseller'],
    img: 'images/c2.jpg',
    images: ['images/c2.jpg','images/c2.jpg','images/c2.jpg'],
    rating: 4.7,
    reviews: 98,
    testimonial: "Teint plus lumineux en 2 semaines — Amélie"
  },
  {
    id: 'c3',
    title: 'Masque purifiant 100ml',
    price: 12.00,
    desc: 'Masque à l’argile fine pour éliminer les impuretés et resserrer les pores sans dessécher la peau. Parfait en cure hebdomadaire pour un teint net.',
    tagline: 'Nettoyant en profondeur, pores raffinés',
    benefits: ['Purifie et absorbe l’excès de sébum', 'Resserre visiblement les pores', 'Formule douce sans dessécher'],
    category: 'Soins',
    tags: [],
    img: 'images/c3.jpg',
    images: ['images/c3.jpg','images/c3.jpg','images/c3.jpg'],
    rating: 4.5,
    reviews: 67,
    testimonial: "Pores resserrés après 2 utilisations — Tarik"
  },
  {
    id: 'c4',
    title: 'Rouge à lèvres N°12',
    price: 15.00,
    desc: 'Rouge à lèvres longue tenue au fini satiné, riche en pigments pour une couleur intense dès la première application. Confortable et hydratant.',
    tagline: 'Couleur intense, tenue confortable',
    benefits: ['Pigmentation riche', 'Confort longue durée', 'Fini satiné lumineux'],
    category: 'Maquillage',
    tags: ['promo'],
    img: 'images/c4.jpg',
    images: ['images/c4.jpg','images/c4.jpg','images/c4.jpg'],
    rating: 4.6,
    reviews: 210,
    testimonial: "Couleur intense et confortable toute la journée — Sara"
  },
  {
    id: 'c5',
    title: 'Palette yeux 6 teintes',
    price: 29.99,
    desc: 'Palette polyvalente comprenant six teintes mattes et satinées pour créer des looks de jour comme de soirée. Couleurs faciles à estomper et longue tenue.',
    tagline: '6 teintes, mille looks',
    benefits: ['Forte tenue', 'Facile à estomper', 'Couleurs complémentaires pour tous les looks'],
    category: 'Maquillage',
    tags: ['bestseller'],
    img: 'images/c5.jpg',
    images: ['images/c5.jpg','images/c5.jpg','images/c5.jpg'],
    rating: 4.7,
    reviews: 321,
    testimonial: "Palette parfaite pour voyager — Noor"
  },
  {
    id: 'c6',
    title: 'Shampooing doux 250ml',
    price: 11.50,
    desc: 'Shampooing sans sulfates qui nettoie délicatement le cuir chevelu tout en préservant l’hydratation naturelle des fibres capillaires. Convient à un usage fréquent.',
    tagline: 'Propreté douce, cheveux sublimés',
    benefits: ['Nettoie sans agresser', 'Sans sulfates', 'Convient à un usage quotidien'],
    category: 'Cheveux',
    tags: [],
    img: 'images/c6.jpg',
    images: ['images/c6.jpg','images/c6.jpg','images/c6.jpg'],
    rating: 4.4,
    reviews: 58,
    testimonial: "Nettoie sans dessécher, top pour usage quotidien — Youssef"
  },
  {
    id: 'c7',
    title: 'Après-shampooing 200ml',
    price: 13.00,
    desc: 'Après-shampooing léger qui démêle instantanément, apporte douceur et brillance sans alourdir la chevelure. Formule enrichie en agents nourrissants.',
    tagline: 'Démêle et nourrit sans alourdir',
    benefits: ['Démêlage facile', 'Apporte brillance', 'Formule légère'],
    category: 'Cheveux',
    tags: ['nouveau'],
    img: 'images/c7.jpg',
    images: ['images/c7.jpg','images/c7.jpg','images/c7.jpg'],
    rating: 4.5,
    reviews: 73,
    testimonial: "Démêle sans alourdir — Emma"
  },
  {
    id: 'c8',
    title: 'Brume hydratante visage',
    price: 10.75,
    desc: 'Brume fraîche et hydratante pour rafraîchir le teint à tout moment de la journée. Contient des ingrédients apaisants pour un effet tonifiant instantané.',
    tagline: 'Un coup de frais, hydratation express',
    benefits: ['Rafraîchit et hydrate', 'Convient pour fixer le maquillage', 'Effet apaisant immédiat'],
    category: 'Soins',
    tags: [],
    img: 'images/c8.jpg',
    images: ['images/c8.jpg','images/c8.jpg','images/c8.jpg'],
    rating: 4.3,
    reviews: 44,
    testimonial: "Rafraîchit vraiment pendant la journée — Paul"
  },
  {
    id: 'c9',
    title: 'Crayon sourcil',
    price: 8.20,
    desc: 'Crayon fin pour des sourcils dessinés avec précision. Texture crémeuse qui se fond naturellement et reste en place toute la journée.',
    tagline: 'Sourcils définis, regard structuré',
    benefits: ['Mine précise', 'Tenue longue durée', 'Effet naturel'],
    category: 'Maquillage',
    tags: [],
    img: 'images/c9.jpg',
    images: ['images/c9.jpg','images/c9.jpg','images/c9.jpg'],
    rating: 4.2,
    reviews: 30,
    testimonial: "Mine fine et naturelle — Ines"
  },

  // Amazon-inspired sample imports (paraphrased)
  {
    id: 'c10',
    title: 'CeraVe Crème Hydratante',
    price: 14.99,
    desc: 'Crème riche formulée avec céramides et acide hyaluronique pour restaurer et maintenir la barrière cutanée. Idéale pour peaux sèches à très sèches.',
    tagline: 'Nutrition réparatrice et confort immédiat',
    benefits: ['Restaure la barrière cutanée', 'Hydratation durable', 'Hypoallergénique, sans parfum'],
    category: 'Soins',
    tags: ['pharmacy','hydration'],
    img: 'images/c10.jpg',
    images: ['images/c10.jpg','images/c10.jpg','images/c10.jpg'],
    rating: 4.6,
    reviews: 410,
    testimonial: "Très bonne crème réparatrice — Karim"
  },
  {
    id: 'c11',
    title: 'The Ordinary Niacinamide 10% + Zinc 1%',
    price: 8.90,
    desc: 'Sérum ciblé pour réguler le sébum et atténuer l’apparence des pores grâce à une forte concentration de niacinamide associée au zinc.',
    tagline: 'Teint unifié, pores affinés',
    benefits: ['Réduit l’excès de sébum', 'Affinement du grain de peau', 'Texture légère, facile à intégrer'],
    category: 'Soins',
    tags: ['serum','niacinamide'],
    img: 'images/c11.jpg',
    images: ['images/c11.jpg','images/c11.jpg','images/c11.jpg'],
    rating: 4.5,
    reviews: 289,
    testimonial: "Réduit la brillance du front — Lea"
  },
  {
    id: 'c12',
    title: 'Maybelline Fit Me Fond de Teint',
    price: 9.99,
    desc: 'Fond de teint fluide pour un fini naturel et modulable. Offre couvrance ajustable et un rendu sans effet masque, disponible en de nombreuses teintes.',
    tagline: 'Un fini naturel, zéro effet masque',
    benefits: ['Couvrance modulable', 'Fini naturel', 'Large gamme de teintes'],
    category: 'Maquillage',
    tags: ['foundation','drugstore'],
    img: 'images/c12.jpg',
    images: ['images/c12.jpg','images/c12.jpg','images/c12.jpg'],
    rating: 4.4,
    reviews: 176,
    testimonial: "Fini naturel et couvrance modulable — Maria"
  },
  {
    id: 'c13',
    title: 'Neutrogena Hydro Boost Gel-Crème',
    price: 12.50,
    desc: 'Gel-crème à base d’acide hyaluronique qui hydrate intensément sans laisser de film gras. Idéal pour les peaux normales à mixtes.',
    tagline: 'Hydratation légère, peau rebondie',
    benefits: ['Hydratation intensive', 'Texture non grasse', 'Idéal sous le maquillage'],
    category: 'Soins',
    tags: ['hydration','gel'],
    img: 'images/c13.jpg',
    images: ['images/c13.jpg','images/c13.jpg','images/c13.jpg'],
    rating: 4.6,
    reviews: 198,
    testimonial: "Hydratation sans film gras — Sophie"
  },
  {
    id: 'c14',
    title: 'L’Oréal Revitalift Sérum',
    price: 19.90,
    desc: 'Sérum anti-âge concentré avec ingrédients actifs pour lisser et raffermir visiblement la peau. Améliore l’éclat et réduit l’apparence des rides.',
    tagline: 'Soin raffermissant, peau plus lisse',
    benefits: ['Raffermit et lisse', 'Réduit l’apparence des rides', 'Texture pénétrante'],
    category: 'Soins',
    tags: ['anti-age'],
    img: 'images/c14.jpg',
    images: ['images/c14.jpg','images/c14.jpg','images/c14.jpg'],
    rating: 4.5,
    reviews: 156,
    testimonial: "Sérum qui a lissé mes rides — Monique"
  },
  {
    id: 'c15',
    title: 'Maybelline Lash Sensational Mascara',
    price: 11.00,
    desc: 'Mascara volumisant qui sépare et enveloppe chaque cil pour un effet volume-poussée, sans paquets. Formule résistante toute la journée.',
    tagline: 'Volume spectaculaire, cils définis',
    benefits: ['Volume sans paquets', 'Sépare et allonge les cils', 'Tenue longue durée'],
    category: 'Maquillage',
    tags: ['mascara','bestseller'],
    img: 'images/c15.jpg',
    images: ['images/c15.jpg','images/c15.jpg','images/c15.jpg'],
    rating: 4.7,
    reviews: 445,
    testimonial: "Mascara incroyable, pas de paquets — Amina"
  }
];
